CREATE DATABASE  IF NOT EXISTS controlestoque;
USE controlestoque;

CREATE TABLE IF NOT EXISTS tb_user(
id INT AUTO_INCREMENT PRIMARY KEY,
name_user VARCHAR(90) NOT NULL,
email_user VARCHAR(90) NOT NULL UNIQUE,
password_user VARCHAR(100) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
