CREATE DATABASE  IF NOT EXISTS controlestoque;
USE controlestoque;

CREATE TABLE IF NOT EXISTS tb_cadastro(
id INT AUTO_INCREMENT PRIMARY KEY,
name_user VARCHAR(90) NOT NULL,
email_user VARCHAR(90) NOT NULL UNIQUE,
password_user VARCHAR(100) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tb_login(
id INT AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(90) NOT NULL UNIQUE,
password_hash VARCHAR(100) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (email) REFERENCES tb_cadastro(email_user)
-- FOREIGN KEY (password_hash) REFERENCES tb_cadastro(password_user) nao incluido por motivos de segurança e boas práticas
);
